#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 13 10:04:27 CET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Schema5_behav -key {Behavioral:schemas:Functional:Schema5} -tclbatch Schema5.tcl -view /home/cocoma-reyes/Documents/VHDL/RISC/Shema1_sim_behav.wcfg -log simulate.log"
xsim Schema5_behav -key {Behavioral:schemas:Functional:Schema5} -tclbatch Schema5.tcl -view /home/cocoma-reyes/Documents/VHDL/RISC/Shema1_sim_behav.wcfg -log simulate.log

